config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :labellings, only: [:create, :destroy]

  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,
    presence: {message: "入力してください！"},
    length: { maximum: 10 }

  validates :content,
    length: { maximum: 30 }

  # validates :status,presence: true

  enum status: { "未着手": 1, "着手中": 2, "完了": 3 }
  enum rank: { "低": 1, "中": 2, "高": 3 }

    # タイトルによる絞り込み
  scope :get_by_title, ->(title) {
    where("title like ?", "%#{title}%")
    }
    # ステータスによる絞り込み
  scope :get_by_status, ->(status) {
    where(status: status)
    }
    #ラベルによる絞り込み
  scope :get_by_label, ->(label) {
    where(id: label)
    }

  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings, dependent: :destroy
  has_many :labelling_labels, through: :labellings, source: :label
  belongs_to :user, optional: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  PER = 5

  # GET /tasks
  def index
    @tasks = Task.all
    # @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    if logged_in?
      @tasks = current_user.tasks.all.order(created_at: :desc).page(params[:page]).per(PER)
    if params[:sort_expired]
      @tasks = Task.all.order(deadline: :desc).page(params[:page]).per(PER)
    end
    if params[:sort_rank]
      @tasks = Task.all.order(rank: :desc).page(params[:page]).per(PER)
    end
    if params[:title].present?
      @tasks = @tasks.get_by_title params[:title]
    end
    if params[:status].present?
      @tasks = @tasks.get_by_status params[:status]
    end
    if params[:label].present?
      @label_id = params[:label].to_i
      @labellings = Labelling.where(label_id: @label_id)
      @tasks = Task.where(id: @labellings.pluck(:task_id)).page(params[:page]).per(PER).where(user_id: current_user.id)
      # binding.irb
      # @tasks = @tasks.get_by_label params[:label]
      # puts @labellings
      # @labellings.each do |labelling|
      #   puts labelling.task_id
      # end
      # @tasks = @labellings.tasks
      # @tasks = Task.where(@labellings)
    end
    else
      redirect_to new_session_path
    end
  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = current_user.tasks.build(task_params)
    # label_list = params[:task][:label_name].split(",")
    if @task.save
      # @task.save_tasks(label_list)
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :content, :rank, :deadline, :status, :user_id, { label_ids: [] })
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :content %>
    <%= form.text_area :content %>

    <%= form.label :rank %>
    <%= form.select :rank,  [["高", "高"], ["中", "中"], ["低", "低"]]%>

    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>

    <%= form.label :status %>
    <%= form.select :status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]]%>

    <%= form.label :label %>
    <%= form.collection_check_boxes( :label_ids, Label.all, :id, :name) %>

    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<button type="button" class="btn btn-warning">
<%= link_to 'ラベル新規作成', new_label_path, :style=>"color:white;"%>
</button>
<button type="button" class="btn btn-warning">
<%= link_to 'タスク新規作成', new_task_path, :style=>"color:white;"%>
</button>

<div class="">
<%= form_tag(tasks_path, :method => 'get' ) do %>
<%= label_tag :title, "タイトル" %>
<%= text_field_tag :title, params[:title] %>
<%= label_tag :status, "ステータス" %>
<%= select_tag :status, options_for_select(Task.statuses), include_blank: true %>
<%= submit_tag '絞り込み' %>
<%= label_tag :label, "ラベル" %>
<%= select_tag :label, options_for_select(Label.pluck(:name, :id)), include_blank: true %>
<a id="settings-link"><%= submit_tag '絞り込み' %></a>

<%# <% end %>
<%# <%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%# <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  <%# <%= form.submit '絞り込み', name: nil %>
<% end %>
</div>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>タスク名</th>
      <th>内容</th>
      <th>優先順位</th>
      <th>終了期限</th>
      <th>状態</th>
      <th>ラベル</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.rank %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td>
          <% task.labels.each do |label| %>
          <%= label.name %>
          <% end %>
        </td>
        <td><%= link_to '詳細', task %></td>
        <td><%= link_to '編集', edit_task_path(task) %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>

  </tbody>
</table>
<button type="button" class="btn btn-primary">
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true" ), :style=>"color:white;"%>
</button>
<button type="button" class="btn btn-success" id ="id_name">
<%= link_to "優先順位でソートする", tasks_path(sort_rank: "true"), :style=>"color:white;"%>
</button>
<br>
<%= paginate @tasks%>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @task.rank %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Labels:</strong>
  <% @task.labels.each do |label| %>
  <%= label.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>