config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :labellings, only: [:create, :destroy]

  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :must_not_destroy_admin

  validates :name,
    presence: {message: "入力してください！"}
    # uniqueness: true, length: { maximum: 30 }

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: {message: "入力してください！"},
    # uniqueness: true,
    format: { with: VALID_EMAIL_REGEX },
    length: { maximum: 255 }

    has_secure_password
    validates :password,
    presence: true, length: { minimum: 6 }

    has_many :tasks, foreign_key: :user_id, dependent: :destroy
    has_many :labels, foreign_key: :user_id, dependent: :destroy
    private

    def must_not_destroy_admin
      if self.admin? && User.where(admin: :true).count == 1
        throw :abort
        flash[:danger] = "これ以上管理者は削除できません"
      end
    end
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user_confirm
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :before_destroy, only: [:destroy]

  def index
    @users = User.select(:id, :name, :email, :password_digest, :created_at, :password, :password_confirmation, :admin)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private
  def admin_user_confirm
    if logged_in? == false
      redirect_to new_session_path
      flash[:danger] = "ログインしてください"
    elsif current_user.admin? == false
    raise Forbidden
    flash[:danger] = "管理者権限がありません。"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation, :admin)
  end

  def before_destroy
    if @user.admin? && User.where(admin: :true).count == 2
      redirect_to admin_users_path
      flash[:danger] = "これ以上管理者は削除できません"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_current_user, only: [:show]
  before_action :logined_user, only: [:new]
  # GET /users
  def index
    @users = User.select(:id, :name, :email, :password_digest, :created_at, :password, :password_confirmation, :admin)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
    end

    def logined_user
      if logged_in? == true
        redirect_to tasks_path
        flash[:danger] = "ログイン中はユーザー登録できません。"
      else
      end
    end

    def ensure_current_user
      if logged_in? == false
        redirect_to new_session_path
        flash[:danger] = "ログインしてください"
      elsif current_user.id != params[:id].to_i
        redirect_to tasks_path
      end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
  </div>

  <div class="field">
  <%= form.label :password %>
  <%= form.password_field :password %>
  </div>

  <div class="field">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>Email</th>
      <th>タスク数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2><%= @user.name %>のマイページ</h2>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="table-responsive">
    <table class ="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>タスク名</th>
          <th>内容</th>
          <th>優先順位</th>
          <th>終了期限</th>
          <th>状態</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.tasks.each do |task| %>
          <tr>
            <td><%= task.title%></td>
            <td><%= task.content %></td>
            <td><%= task.rank %></td>
            <td><%= task.deadline %></td>
            <td><%= task.status %></td>
            <td><%= link_to '編集', edit_task_path(task) %></td>
            <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  </div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'タスク一覧へ', tasks_path %>